/**
 * Doorson IAM API spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * <p>
 * The version of the OpenAPI document: 0.0.6
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.gpor0.jaffas.endpoints.model;

import jakarta.json.bind.annotation.JsonbProperty;
import java.util.List;

public class SyncRolePermissions {

    @JsonbProperty("rolePermissions")
    private List<SyncRole> rolePermissions = null;

    @JsonbProperty("permissions")
    private List<SyncPermission> permissions = null;

    /**
     * Get rolePermissions
     * @return rolePermissions
     **/
    public List<SyncRole> getRolePermissions() {
        return rolePermissions;
    }

    /**
     * Set rolePermissions
     **/
    public void setRolePermissions(List<SyncRole> rolePermissions) {
        this.rolePermissions = rolePermissions;
    }

    public SyncRolePermissions rolePermissions(List<SyncRole> rolePermissions) {
        this.rolePermissions = rolePermissions;
        return this;
    }

    public SyncRolePermissions addRolePermissionsItem(SyncRole rolePermissionsItem) {
        this.rolePermissions.add(rolePermissionsItem);
        return this;
    }

    /**
     * Get permissions
     * @return permissions
     **/
    public List<SyncPermission> getPermissions() {
        return permissions;
    }

    /**
     * Set permissions
     **/
    public void setPermissions(List<SyncPermission> permissions) {
        this.permissions = permissions;
    }

    public SyncRolePermissions permissions(List<SyncPermission> permissions) {
        this.permissions = permissions;
        return this;
    }

    public SyncRolePermissions addPermissionsItem(SyncPermission permissionsItem) {
        this.permissions.add(permissionsItem);
        return this;
    }


    /**
     * Create a string representation of this pojo.
     **/
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SyncRolePermissions {\n");

        sb.append("    rolePermissions: ").append(toIndentedString(rolePermissions)).append("\n");
        sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

