/**
 * Doorson IAM API spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * <p>
 * The version of the OpenAPI document: 0.0.6
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.gpor0.jaffas.endpoints.model;

import jakarta.json.bind.annotation.JsonbProperty;
import java.util.ArrayList;
import java.util.List;

public class SyncRole {

    @JsonbProperty("name")
    private String name;

    @JsonbProperty("description")
    private String description;

    @JsonbProperty("permissions")
    private List<String> permissions = new ArrayList<>();

    /**
     * Get name
     * @return name
     **/
    public String getName() {
        return name;
    }

    /**
     * Set name
     **/
    public void setName(String name) {
        this.name = name;
    }

    public SyncRole name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get description
     * @return description
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Set description
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    public SyncRole description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get permissions
     * @return permissions
     **/
    public List<String> getPermissions() {
        return permissions;
    }

    /**
     * Set permissions
     **/
    public void setPermissions(List<String> permissions) {
        this.permissions = permissions;
    }

    public SyncRole permissions(List<String> permissions) {
        this.permissions = permissions;
        return this;
    }

    public SyncRole addPermissionsItem(String permissionsItem) {
        this.permissions.add(permissionsItem);
        return this;
    }


    /**
     * Create a string representation of this pojo.
     **/
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SyncRole {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

