/**
 * Doorson IAM API spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * <p>
 * The version of the OpenAPI document: 0.0.6
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.gpor0.jaffas.endpoints;


import com.github.gpor0.jaffas.endpoints.model.SyncRolePermissions;

import javax.ws.rs.*;

/**
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 */

@Path("/")
public interface PermissionsApi {
    /**
     * Sync permissions for application
     * <p>
     * Sync application permissions
     */
    @PUT
    @Path("/permissions")
    @Consumes({"application/json"})
    @Produces({"application/json"})
    void syncPermissions(@HeaderParam("Authorization") String authHeaderValue, @QueryParam("application") String application, SyncRolePermissions syncRolePermissions);
}

